#!/bin/bash

# Load environment variables from .env file
set -o allexport
source .env
set +o allexport

AWS_PROFILE=App

# Ensure AWS SSO session is active
aws sso login --profile $AWS_PROFILE

# Get the SSO access token
SSO_CACHE_FILE=$(ls -t ~/.aws/sso/cache | head -1)
SSO_ACCESS_TOKEN=$(cat ~/.aws/sso/cache/$SSO_CACHE_FILE | jq -r '.accessToken')

# Use the SSO access token to get the role credentials
ROLE_CREDENTIALS=$(aws sso get-role-credentials \
  --account-id $AWS_ACCOUNT_ID \
  --role-name $AWS_ROLE_NAME \
  --access-token $SSO_ACCESS_TOKEN \
  --profile $AWS_PROFILE)

# Extract the credentials
export AWS_ACCESS_KEY_ID=$(echo $ROLE_CREDENTIALS | jq -r '.roleCredentials.accessKeyId')
export AWS_SECRET_ACCESS_KEY=$(echo $ROLE_CREDENTIALS | jq -r '.roleCredentials.secretAccessKey')
export AWS_SESSION_TOKEN=$(echo $ROLE_CREDENTIALS | jq -r '.roleCredentials.sessionToken')

rm .env.aws

cat <<EOT >> .env.aws
## AWS Configuration - DO NOT CHANGE - AUTOGENERATED ##
AWS_REGION=$AWS_REGION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
EOT

# Start Docker containers
docker-compose up -d
